---
- name: Play with SSH
  hosts: web
  vars:
    user_name: moti
  tasks:
  - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
    community.crypto.openssh_keypair:
      path: /tmp/id_ssh_rsa
    delegate_to: 127.0.0.1 #will create the ssh key pait only on the server.

  - name: Add the user to remote nodes
    user:
      name: "{{ user_name }}"
      comment: "{{ user_name }}"
      state: present
    become: yes

  - name: Copy SSH key to remote node
    copy:
      src: /tmp/id_ssh_rsa.pub
      dest: /tmp"
    become: yes
  
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: "{{ user_name }}"
      state: present
      key: "{{ lookup('file', '/tmp/id_ssh_rsa.pub') }}"
    become: yes
